### ISSUE TITLE
Determine what platform we will develop a interactive prototype on.

### ISSUE THREAD

**Issue by davo27** [deco3500/TheLocalCode#17]
# **Description**
Before we can start to build a demo program to show of features, we need to determine a platform to develop for. We have two different AR SDK's we can use for just about any platform so this should come down to what tech we all have available to work on.

# **Dependencies**
- all tech we have
- what everyone already knows about the tech we have.

# **Milestone**
List of features you intend to have done and in Master by Checkpoint 1
- [ ] Understand all the tech we have access to
- [ ] Know what we are all comfortable developing a prototype on
- [ ] Decided on what we want to prototype in
- [ ] Generate some stubs in the GitHub showing this.
