### ISSUE TITLE
Test out paper prototype

### ISSUE THREAD

**Issue by davo27** [deco3500/TheLocalCode#18]
# **Description**
We need to test out our design via the paper prototype and digital prototype. We want to do this to gain information about what the students want from the AR app. We want to make sure our design solves the problem of news circulation & use of modern tech in schools.

# **Dependencies**
- Paper prototype complete
- digital mock up complete
- testing procedure documented.

# **Milestone**
List of features you intend to have done and in Master by Checkpoint 1
- [x] paper prototype completed
- [ ] digital mock ups done
- [x] Procedure for testing documented
- [x] Tested on a range of students.

**Comment by nahwellmaybe** [comment]
I will link all the paper prototype images here
The numbers are the order in which they should be accessed

![](https://i.gyazo.com/6658d8cd8f5c5b98c457ec70e655216b.png) (phone)

![](https://i.gyazo.com/943813742e2094a427db0c94953daaf8.png) (1, 8, 12)

![](https://i.gyazo.com/71b40bdbd5209eaf5a940089fcb25c25.png) (2, 5)

![](https://i.gyazo.com/2ee40c12fd90561e1fbaf866f7d9efb6.png) (3)

![](https://i.gyazo.com/e18a173fa6d0c05e7afd7125d6974b38.png) (4) (to show they selected the basketball, to be placed over the existing basketball)

![](https://i.gyazo.com/0868eddb09e6a2ebafae413794d137ad.png) (6)

![](https://i.gyazo.com/4db6e66a5456ad4a4a1dfe2c741de145.png) (7)

![](https://i.gyazo.com/bf53fbad229d8e80b4da2744ad251cfd.png) (9, 11)

![](https://i.gyazo.com/87e7f2c28e303078ceaac2e31203380b.png) (10)

![](https://i.gyazo.com/b8ae5f88cc4926afa43b9ad510970acf.png) (13)

![](https://i.gyazo.com/2287106a0978e91422a883b96c1bc3c8.png) (14)

end of testing
I will write up and post the method of the testing shortly

**Comment by nahwellmaybe** [comment]
attached is the questionnaire and procedure for testing

https://docs.google.com/document/d/1lQB0S9cw-8-Wf8oHfYbSv0hZZm1CmTnkDpoOqQDSMCY/edit

**Comment by farahidahanim** [comment]
oli can u add me to gdrvie. i cant access the link

**Comment by nahwellmaybe** [comment]
[paper prototype test results.pdf](https://github.com/deco3500/TheLocalCode/files/512963/paper.prototype.test.results.pdf)

test results

**Comment by farahidahanim** [comment]
https://docs.google.com/spreadsheets/d/1M6Trh5NLCUZm2ZRQlK2PJf8h7UyjJb2Bqcs0Vy_9_3w/edit#gid=1246157867 

this is test result that carried by me.

**Comment by davo27** [comment]
Paper prototypes revealed some flaws with the UI design which will be addressed with the next prototype, alogn with concept changes
