### ISSUE TITLE
analyse user feedback 

### ISSUE THREAD

**Issue by farahidahanim** [deco3500/TheLocalCode#19]
# Task
We need to break down the results of our testing and make changes to our prototype based on that.

- [x] analyse user requirement after testing the prototype. 
- [x] analyse the result from the prototype.  
- [x] interpret result  
- [x] document the analysis 
- [x] discuss the result with the team 

# Dependencies
So we need to complete testing before this task can be started.

**Comment by davo27** [comment]
All discuessed in persona and links heavily to UI design. Concept was liked.
